name: Build and Publish Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.created=$GITHUB_RUN_DATE
            org.opencontainers.image.authors=${{ env.AUTHOR }}
            org.opencontainers.image.url=https://hub.docker.com/r/${{ github.repository }}
            org.opencontainers.image.source=$GITHUB_SERVER_URL/${{ github.repository }}

      - name: Install Devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build and publish base-ubuntu container
        run: |
          cd src/base-ubuntu
          devcontainer build --workspace-folder . --image-name ${{ github.repository }}/base-ubuntu:latest --platform linux/arm64,linux/amd64 \
          --output type=registry \
          --label ${{ steps.meta.outputs.labels }} \
          --tag ${{ steps.meta.outputs.tags }}

      - name: Build and publish node container
        run: |
          cd src/node
          devcontainer build --workspace-folder . --image-name ${{ github.repository }}/node:latest --platform linux/arm64,linux/amd64 \
          --output type=registry \
          --label ${{ steps.meta.outputs.labels }} \
          --tag ${{ steps.meta.outputs.tags }}

      - name: Build and publish python container
        run: |
          cd src/python
          devcontainer build --workspace-folder . --image-name ${{ github.repository }}/python:latest --platform linux/arm64,linux/amd64 \
          --output type=registry \
          --label ${{ steps.meta.outputs.labels }} \
          --tag ${{ steps.meta.outputs.tags }}
