name: Build and Publish Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Job-specific permissions that override workflow-level permissions
    permissions:
      contents: read # Required to check out the repository
      packages: write # Required to push packages to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}

      - name: Process metadata
        run: |
          # Convert newline-separated labels to multiple --label arguments
          LABEL_ARGS=$(echo "${{ steps.meta.outputs.labels }}" | while IFS= read -r line; do
            [ -n "$line" ] && echo -n "--label \"$line\" "
          done)
          echo "LABEL_ARGS=$LABEL_ARGS" >> $GITHUB_ENV

      - name: Install Devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Debug GITHUB_TOKEN permissions for user and repository
        run: |
          echo "Testing GITHUB_TOKEN permissions for user namespace..."
          curl -s -w "\nHTTP_STATUS: %{http_code}\n" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/user/packages?package_type=container" > user_packages.json
          cat user_packages.json

          echo "Testing GITHUB_TOKEN permissions for repository packages..."
          curl -s -w "\nHTTP_STATUS: %{http_code}\n" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/${{ github.repository }}/packages?package_type=container" > repo_packages.json
          cat repo_packages.json

      - name: Build and publish base-ubuntu container
        run: |
          cd src/base-ubuntu
          devcontainer build --workspace-folder . \
            --image-name ghcr.io/${{ github.repository }}:base-ubuntu \
            --platform linux/arm64,linux/amd64 \
            --output type=registry \
            ${{ env.LABEL_ARGS }}

      - name: Build and publish node container
        run: |
          cd src/node
          devcontainer build --workspace-folder . \
            --image-name ghcr.io/${{ github.repository }}:node \
            --platform linux/arm64,linux/amd64 \
            --output type=registry \
            ${{ env.LABEL_ARGS }}

      - name: Build and publish python container
        run: |
          cd src/python
          devcontainer build --workspace-folder . \
            --image-name ghcr.io/${{ github.repository }}:python \
            --platform linux/arm64,linux/amd64 \
            --output type=registry \
            ${{ env.LABEL_ARGS }}
